### PR TITLE
11 add some simple styles to login and signup components

### LINKED ISSUE #11: Add some simple styles to login and signup components

### PR DESCRIPTION
**Pull request by DDuran19**

### CODE REVIEW

**Comment by DDuran19** [comment]
image
image

**Review by directormac — DISMISSED** [review]

**Comment by DDuran19** [comment]
@directormac  in relation to #10 where we should use pnpm instead of npm, how can we remove the commit in this branch where I added the overrides in package json.

can we leave it as it is? I tried reviewing the changed files, looks like it was unaffected

**Comment by directormac** [comment]
> @directormac in relation to #10 where we should use pnpm instead of npm, how can we remove the commit in this branch where I added the overrides in package json.
> 
> can we leave it as it is? I tried reviewing the changed files, looks like it was unaffected

You can remove it and re initialize your branch in pnpm again so lockfiles sync.

**Comment by DDuran19** [comment]
I was referring to this  pull request, whether it should be approved or not

**Comment by directormac** [comment]
> I was referring to this pull request, whether it should be approved or not

this one looks good should be approved.

**Pull request merged**
